name: Node.js CI

on:
  push:
    branches: [ "cd" ]
  pull_request:
    branches: [ "cd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build -t udagram-api-feed ./udagram-api-feed
    - run: docker build -t udagram-api-user ./udagram-api-user
    - run: docker build -t udagram-frontend ./udagram-frontend
    - run: docker build -t reverseproxy ./udagram-reverseproxy

    - run: docker tag udagram-frontend letu071299/udagram-frontend:v1
    - run: docker tag udagram-api-user letu071299/udagram-api-user:v1
    - run: docker tag udagram-api-feed letu071299/udagram-api-feed:v1
    - run: docker tag reverseproxy letu071299/reverseproxy:v1

    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    
    - run: docker push letu071299/udagram-frontend:v1
    - run: docker push letu071299/udagram-api-user:v1
    - run: docker push letu071299/udagram-api-feed:v1
    - run: docker push letu071299/reverseproxy:v1