# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "cd" ]
  pull_request:
    branches: [ "cd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # creates images
    - run: docker-compose -f docker-compose-build.yaml build --parallel

    # tags images to docker
    - run: docker tag udagram-frontend:local letu071299/udagram-frontend:v1
    - run: docker tag udagram-api-user letu071299/udagram-api-user:v1
    - run: docker tag udagram-api-feed letu071299/udagram-api-feed:v1
    - run: docker tag reverseproxy letu071299/reverseproxy:v1

    # logins to DockerHub
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    # pushes to DockerHub
    - run: docker push letu071299/udagram-frontend:v1
    - run: docker push letu071299/udagram-api-user:v1
    - run: docker push letu071299/udagram-api-feed:v1
    - run: docker push letu071299/reverseproxy:v1