name: Node.js CI

on:
  push:
    branches: [ "cd" ]
  pull_request:
    branches: [ "cd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - run: docker-compose -f docker-compose-build.yaml build --parallel

    - run: docker build -t reverseproxy ./udagram-reverseproxy
    - run: docker build -t udagram-api-feed ./udagram-reverseproxy
    - run: docker build -t udagram-api-user ./udagram-reverseproxy
    - run: docker build -t udagram-frontend ./udagram-reverseproxy

    - run: docker tag udagram-frontend letu071299/udagram-frontend:local
    - run: docker tag udagram-api-user letu071299/udagram-api-user:v4a
    - run: docker tag udagram-api-feed letu071299/udagram-api-feed:v4a
    - run: docker tag reverseproxy letu071299/reverseproxy:v4a
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    
    - run: docker push letu071299/udagram-frontend:local
    - run: docker push letu071299/udagram-api-user:v4a
    - run: docker push letu071299/udagram-api-feed:v4a
    - run: docker push letu071299/reverseproxy:v4a