name: Node.js CI

on:
  push:
    branches: [ "cd" ]
  pull_request:
    branches: [ "cd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # creates images
    - run: 'docker build -t udagram-frontend ./udagram-frontend'
    - run: 'docker build -t udagram-reverseproxy ./udagram-reverseproxy'
    - run: 'docker build -t udagram-api-feed ./udagram-api-feed'
    - run: 'docker build -t udagram-api-user ./udagram-api-user'

    # tags images to docker
    - run: 'docker tag udagram-reverseproxy letu071299/udagram-reverseproxy:v4a'
    - run: 'docker tag udagram-api-feed letu071299/udagram-api-feed:v4a'
    - run: 'docker tag udagram-api-user letu071299/udagram-api-user:v4a'
    - run: 'docker tag udagram-frontend letu071299/udagram-frontend:local'

    # logins to DockerHub
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    # pushes to DockerHub
    - run: 'docker push letu071299/udagram-reverseproxy:v4a'
    - run: 'docker push letu071299/udagram-api-feed:v4a'
    - run: 'docker push letu071299/udagram-api-user:v4a'
    - run: 'docker push letu071299/udagram-frontend:local'